import fetchMock from "fetch-mock";

export const getTopStories = () => {
  fetchMock.get(
    "/getTopStories",
    {
      body: [{
		"section": "",
		"subsection": "",
		"title": "",
		"abstract": "",
		"url": "",
		"uri": "nyt://promo/15cdf3ee-e241-518b-9d3b-816e81b4ef37",
		"byline": "",
		"item_type": "Promo",
		"updated_date": "2022-08-05T05:26:04-04:00",
		"created_date": "2022-08-04T06:07:52-04:00",
		"published_date": "2022-08-04T06:07:52-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": [],
		"org_facet": [],
		"per_facet": [],
		"geo_facet": [],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/03/04ukraine-briefing-promo1am/04ukraine-briefing-promo1am-superJumbo-v2.jpg",
			"format": "Super Jumbo",
			"height": 1366,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Residents receiving water in Druzhkivka on Wednesday.",
			"copyright": "David Guttenfelder for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/03/04ukraine-briefing-promo1am/04ukraine-briefing-promo1am-threeByTwoSmallAt2X-v2.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Residents receiving water in Druzhkivka on Wednesday.",
			"copyright": "David Guttenfelder for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/03/04ukraine-briefing-promo1am/04ukraine-briefing-promo1am-thumbLarge-v2.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Residents receiving water in Druzhkivka on Wednesday.",
			"copyright": "David Guttenfelder for The New York Times"
		}],
		"short_url": ""
	}, {
		"section": "",
		"subsection": "",
		"title": "",
		"abstract": "",
		"url": "",
		"uri": "nyt://promo/1200396d-4bdf-50c0-8daf-121172f764e0",
		"byline": "",
		"item_type": "Promo",
		"updated_date": "2022-08-05T06:17:00-04:00",
		"created_date": "2022-08-04T10:35:46-04:00",
		"published_date": "2022-08-04T10:35:46-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": [],
		"org_facet": [],
		"per_facet": [],
		"geo_facet": [],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04griner-blog-promo-1030am/04griner-blog-promo-1030am-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Brittney Griner was found guilty of drug charges by a Russian court on Thursday.",
			"copyright": "Pool photo by Kirill Kudryavtsev"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04griner-blog-promo-1030am/04griner-blog-promo-1030am-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Brittney Griner was found guilty of drug charges by a Russian court on Thursday.",
			"copyright": "Pool photo by Kirill Kudryavtsev"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04griner-blog-promo-1030am/04griner-blog-promo-1030am-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Brittney Griner was found guilty of drug charges by a Russian court on Thursday.",
			"copyright": "Pool photo by Kirill Kudryavtsev"
		}],
		"short_url": ""
	}, {
		"section": "world",
		"subsection": "asia",
		"title": "Chinese Missiles Strike Seas Off Taiwan, and Some Land Near Japan",
		"abstract": "A day after Nancy Pelosi’s trip, China has begun military drills near Taiwan. They appear to be designed as a trial run for sealing off the island. Five missiles landed in Japanese waters.",
		"url": "https://www.nytimes.com/2022/08/03/world/asia/taiwan-china-military-exercises.html",
		"uri": "nyt://article/f1c281a2-7496-5419-8ce5-5e59dd34ac8e",
		"byline": "By Chris Buckley, Amy Chang Chien, Eric Schmitt and David E. Sanger",
		"item_type": "Article",
		"updated_date": "2022-08-05T06:19:40-04:00",
		"created_date": "2022-08-03T21:44:46-04:00",
		"published_date": "2022-08-03T21:44:46-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["International Relations", "Defense and Military Forces", "Missiles and Missile Defense Systems", "United States International Relations"],
		"org_facet": ["People's Liberation Army (China)", "House of Representatives"],
		"per_facet": ["Pelosi, Nancy", "Biden, Joseph R Jr", "Xi Jinping"],
		"geo_facet": ["Taiwan", "China", "Japan"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/world/04taiwan-drills-sub1/04taiwan-drills-sub1-superJumbo-v3.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Chinese military helicopters off the shore of Fujian Province, just across the strait from Taiwan, on Thursday.",
			"copyright": "Hector Retamal/Agence France-Presse — Getty Images"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04taiwan-drills-sub1/04taiwan-drills-sub1-threeByTwoSmallAt2X-v3.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Chinese military helicopters off the shore of Fujian Province, just across the strait from Taiwan, on Thursday.",
			"copyright": "Hector Retamal/Agence France-Presse — Getty Images"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04taiwan-drills-sub1/04taiwan-drills-sub1-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Chinese military helicopters off the shore of Fujian Province, just across the strait from Taiwan, on Thursday.",
			"copyright": "Hector Retamal/Agence France-Presse — Getty Images"
		}],
		"short_url": "https://nyti.ms/3vCbkYE"
	}, {
		"section": "world",
		"subsection": "middleeast",
		"title": "Beirut Port Silos Partly Collapse on Second Anniversary of Blast",
		"abstract": "The silos were damaged in the 2020 port explosion and government officials had warned that they could collapse.",
		"url": "https://www.nytimes.com/2022/08/04/world/middleeast/beirut-port-silos-collapse-2020-explosion.html",
		"uri": "nyt://article/2f73ff2d-7cd9-5a31-8343-911de731db09",
		"byline": "By Raja Abdulrahim",
		"item_type": "Article",
		"updated_date": "2022-08-04T22:12:09-04:00",
		"created_date": "2022-08-04T14:56:28-04:00",
		"published_date": "2022-08-04T14:56:28-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Beirut, Lebanon, Explosions (2020)", "Ports", "Accidents and Safety", "Politics and Government", "Hazardous and Toxic Substances"],
		"org_facet": [],
		"per_facet": [],
		"geo_facet": [],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/world/04beirut-silos-3/merlin_211041111_79f8b741-48ca-49ee-957f-5acd4d3e9021-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "The smoldering remains of grain silos at the Port of Beirut, after a partial collapse on Thursday.",
			"copyright": "Kameel Rayes/Agence France-Presse — Getty Images"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04beirut-silos-3/merlin_211041111_79f8b741-48ca-49ee-957f-5acd4d3e9021-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "The smoldering remains of grain silos at the Port of Beirut, after a partial collapse on Thursday.",
			"copyright": "Kameel Rayes/Agence France-Presse — Getty Images"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04beirut-silos-3/merlin_211041111_79f8b741-48ca-49ee-957f-5acd4d3e9021-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "The smoldering remains of grain silos at the Port of Beirut, after a partial collapse on Thursday.",
			"copyright": "Kameel Rayes/Agence France-Presse — Getty Images"
		}],
		"short_url": "https://nyti.ms/3P1RmgO"
	}, {
		"section": "world",
		"subsection": "asia",
		"title": "With 5 Missiles, China Sends Stark Signal to Japan and U.S. on Taiwan",
		"abstract": "By firing into Japanese waters, Beijing is warning that both countries will become targets if they should come to the aid of Taiwan in any conflict.",
		"url": "https://www.nytimes.com/2022/08/04/world/asia/china-japan-taiwan-missiles.html",
		"uri": "nyt://article/e008036d-5be2-59a6-ad66-c51f8b1baae5",
		"byline": "By Ben Dooley",
		"item_type": "Article",
		"updated_date": "2022-08-05T02:57:34-04:00",
		"created_date": "2022-08-04T14:26:20-04:00",
		"published_date": "2022-08-04T14:26:20-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["United States International Relations", "War and Armed Conflicts"],
		"org_facet": ["Liberal Democratic Party (Japan)"],
		"per_facet": ["Abe, Shinzo"],
		"geo_facet": ["Beijing (China)", "China", "Japan", "Tokyo (Japan)", "United States", "Okinawa and Other Ryukyu Islands (Japan)"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/world/04japan-missiles-top/04japan-missiles-top-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 587,
			"width": 880,
			"type": "image",
			"subtype": "photo",
			"caption": "This photograph released by the People’s Liberation Army of China purports to show conventional missiles being test fired into waters off the east coast of Taiwan from an undisclosed location in China.",
			"copyright": "Eastern Theatre Command, via Reuters"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04japan-missiles-top/04japan-missiles-top-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "This photograph released by the People’s Liberation Army of China purports to show conventional missiles being test fired into waters off the east coast of Taiwan from an undisclosed location in China.",
			"copyright": "Eastern Theatre Command, via Reuters"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04japan-missiles-top/04japan-missiles-top-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "This photograph released by the People’s Liberation Army of China purports to show conventional missiles being test fired into waters off the east coast of Taiwan from an undisclosed location in China.",
			"copyright": "Eastern Theatre Command, via Reuters"
		}],
		"short_url": "https://nyti.ms/3SE9lgH"
	}, {
		"section": "world",
		"subsection": "europe",
		"title": "Mines, Fires, Rockets: The Ravages of War Bedevil Ukraine’s Farmers",
		"abstract": "A deal allowing ships to start carrying grain from Ukraine solved a logistical problem, but it left a more pressing one for Ukrainian farmers: growing and reaping crops in a war zone.",
		"url": "https://www.nytimes.com/2022/08/04/world/europe/ukraine-russia-farms-farming-wheat-barley.html",
		"uri": "nyt://article/fcb4d847-60c6-5c84-8067-8cbe6369a087",
		"byline": "By Andrew E. Kramer and David Guttenfelder",
		"item_type": "Article",
		"updated_date": "2022-08-05T00:36:31-04:00",
		"created_date": "2022-08-04T00:01:18-04:00",
		"published_date": "2022-08-04T00:01:18-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["International Relations", "War and Armed Conflicts", "Russian Invasion of Ukraine (2022)", "Agriculture and Farming"],
		"org_facet": [],
		"per_facet": ["Zelensky, Volodymyr"],
		"geo_facet": ["Black Sea", "Russia", "Ukraine"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/03/world/03UkraineFarmingPromo/merlin_210921504_80be4cf5-f2f6-4528-9fce-259d6bceb410-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1366,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "In the fields on a recent, sweltering afternoon during the harvest, flames crackled through the stubble of the recently harvested wheat crop of Vasily Tabachnyuk, picking up with gusts of wind.",
			"copyright": "David Guttenfelder for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/03/world/03UkraineFarmingPromo/03UkraineFarming01-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "In the fields on a recent, sweltering afternoon during the harvest, flames crackled through the stubble of the recently harvested wheat crop of Vasily Tabachnyuk, picking up with gusts of wind.",
			"copyright": "David Guttenfelder for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/03/world/03UkraineFarmingPromo/03UkraineFarming01-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "In the fields on a recent, sweltering afternoon during the harvest, flames crackled through the stubble of the recently harvested wheat crop of Vasily Tabachnyuk, picking up with gusts of wind.",
			"copyright": "David Guttenfelder for The New York Times"
		}],
		"short_url": "https://nyti.ms/3cTILQ0"
	}, {
		"section": "world",
		"subsection": "middleeast",
		"title": "After 5 Years of Terror, a Town in Libya Finds Justice Frustratingly Elusive",
		"abstract": "Political chaos in the country has left little room for the reconciliation that many see as necessary for peace. Few places feel that more than Tarhuna, where a murderous band of brothers long menaced residents.",
		"url": "https://www.nytimes.com/2022/07/31/world/middleeast/tarhuna-libya-graves.html",
		"uri": "nyt://article/be49e0f3-8701-5d1c-9c95-0024bce0008d",
		"byline": "By Vivian Yee",
		"item_type": "Article",
		"updated_date": "2022-08-04T06:58:04-04:00",
		"created_date": "2022-07-31T11:58:01-04:00",
		"published_date": "2022-07-31T11:58:01-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Politics and Government", "Murders, Attempted Murders and Homicides"],
		"org_facet": [],
		"per_facet": ["Kani Family", "Bashagha, Fathi", "Hifter, Khalifa", "Qaddafi, Muammar el-", "Dbeiba, Abdul Hamid"],
		"geo_facet": ["Libya", "TARHUNA (LIBYA)", "Tripoli (Libya)"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/01/world/01LibyaPolitics01/merlin_208792968_c01e7bda-04e9-4d40-ac03-51abf09133c8-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1536,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "The Kani brothers’ notorious detention center in the town of Tarhuna. The brothers found allies at different times on both sides of Libya’s political divide.",
			"copyright": "Laura Boushnak for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/01/world/01LibyaPolitics01/01LibyaPolitics01-threeByTwoSmallAt2X-v2.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "The Kani brothers’ notorious detention center in the town of Tarhuna. The brothers found allies at different times on both sides of Libya’s political divide.",
			"copyright": "Laura Boushnak for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/01/world/01LibyaPolitics01/01LibyaPolitics01-thumbLarge-v2.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "The Kani brothers’ notorious detention center in the town of Tarhuna. The brothers found allies at different times on both sides of Libya’s political divide.",
			"copyright": "Laura Boushnak for The New York Times"
		}],
		"short_url": "https://nyti.ms/3p1a2mF"
	}, {
		"section": "world",
		"subsection": "middleeast",
		"title": "As Iran Talks of Nuclear Advances, Negotiations With U.S. Restart",
		"abstract": "Envoys from both countries gathered for another effort to restore the 2015 agreement to limit Tehran’s nuclear program. Expectations are low.",
		"url": "https://www.nytimes.com/2022/08/04/world/middleeast/us-iran-nuclear-deal.html",
		"uri": "nyt://article/a5f037b7-28dc-53bf-8b2d-54e9ac7548ca",
		"byline": "By Steven Erlanger",
		"item_type": "Article",
		"updated_date": "2022-08-04T22:22:07-04:00",
		"created_date": "2022-08-04T10:16:58-04:00",
		"published_date": "2022-08-04T10:16:58-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["International Relations", "Nuclear Weapons", "United States International Relations", "Embargoes and Sanctions", "Arms Control and Limitation and Disarmament"],
		"org_facet": ["International Atomic Energy Agency"],
		"per_facet": [],
		"geo_facet": ["Iran"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/world/04iran-nuclear/merlin_211032591_97f60d72-174f-44a9-a0c9-7739111fc9dc-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Ali Bagheri Kani, front, Iran’s chief nuclear negotiator, in Vienna on Thursday. He said that the burden was on Washington to resuscitate the deal.",
			"copyright": "Lisa Leutner/Reuters"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04iran-nuclear/merlin_211032591_97f60d72-174f-44a9-a0c9-7739111fc9dc-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Ali Bagheri Kani, front, Iran’s chief nuclear negotiator, in Vienna on Thursday. He said that the burden was on Washington to resuscitate the deal.",
			"copyright": "Lisa Leutner/Reuters"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04iran-nuclear/04iran-nuclear-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Ali Bagheri Kani, front, Iran’s chief nuclear negotiator, in Vienna on Thursday. He said that the burden was on Washington to resuscitate the deal.",
			"copyright": "Lisa Leutner/Reuters"
		}],
		"short_url": "https://nyti.ms/3buuBo9"
	}, {
		"section": "world",
		"subsection": "asia",
		"title": "U.S. Bolsters Aid for Cambodia Amid Efforts to Ease Global Food Crisis",
		"abstract": "Secretary of State Antony J. Blinken announced $25 million over five years to support an initiative that will work with farmers and others in the agriculture industry to get produce to more markets.",
		"url": "https://www.nytimes.com/2022/08/04/world/asia/cambodia-agriculture-aid.html",
		"uri": "nyt://article/384e77fa-bd75-55cd-983b-bf461f9b7f11",
		"byline": "By Edward Wong",
		"item_type": "Article",
		"updated_date": "2022-08-04T22:19:42-04:00",
		"created_date": "2022-08-04T08:55:17-04:00",
		"published_date": "2022-08-04T08:55:17-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["United States International Relations", "Food Insecurity", "Russian Invasion of Ukraine (2022)", "Agriculture and Farming", "Grain"],
		"org_facet": ["Assn of Southeast Asian Nations", "World Food Program", "United States Agency for International Development", "United Nations"],
		"per_facet": ["Borrell Fontelles, Josep", "Guterres, Antonio", "Putin, Vladimir V", "Blinken, Antony J"],
		"geo_facet": ["Cambodia"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/world/04Cambodia01/merlin_210938925_e875b5c2-bc7b-489b-abbc-206e2c3de0a5-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Selling fish near the Mekong River in Phnom Penh, Cambodia, on Tuesday. The problem of global food insecurity has become more pressing since Russia’s invasion of Ukraine.",
			"copyright": "Mohd Rasfan/Agence France-Presse — Getty Images"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04Cambodia01/merlin_210938925_e875b5c2-bc7b-489b-abbc-206e2c3de0a5-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Selling fish near the Mekong River in Phnom Penh, Cambodia, on Tuesday. The problem of global food insecurity has become more pressing since Russia’s invasion of Ukraine.",
			"copyright": "Mohd Rasfan/Agence France-Presse — Getty Images"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04Cambodia01/04Cambodia01-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Selling fish near the Mekong River in Phnom Penh, Cambodia, on Tuesday. The problem of global food insecurity has become more pressing since Russia’s invasion of Ukraine.",
			"copyright": "Mohd Rasfan/Agence France-Presse — Getty Images"
		}],
		"short_url": "https://nyti.ms/3Jwf185"
	}, {
		"section": "world",
		"subsection": "europe",
		"title": "Irish Farmers Help Save a Bird Whose Calls Used to Herald Summer",
		"abstract": "The corncrake’s cry, thought to be loud and harsh, is a poignant reminder for older people of the advent of warmer weather. Efforts are underway to preserve its call for younger generations.",
		"url": "https://www.nytimes.com/2022/08/04/world/europe/ireland-corncrake.html",
		"uri": "nyt://article/bb63b881-e439-5d00-aa2b-7a3ab3cf4ba3",
		"byline": "By Ed O’Loughlin",
		"item_type": "Article",
		"updated_date": "2022-08-04T22:10:12-04:00",
		"created_date": "2022-08-04T08:13:36-04:00",
		"published_date": "2022-08-04T08:13:36-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Agriculture and Farming", "Birds"],
		"org_facet": ["European Union"],
		"per_facet": [],
		"geo_facet": ["County Cork (Ireland)", "County Mayo (Ireland)", "Ireland"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/07/26/world/26Ireland-corncrake1/merlin_209872779_d8634baf-d47f-4105-bb5e-0b52855d892d-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "John Carey, the director of Corncrake Life, a conservation effort created to increase the birds’ population, with Margaret Gaughan, a farmer participating in the project, in Belmullet, Ireland.",
			"copyright": "Paulo Nunes dos Santos for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/07/26/world/26Ireland-corncrake1/merlin_209872779_d8634baf-d47f-4105-bb5e-0b52855d892d-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "John Carey, the director of Corncrake Life, a conservation effort created to increase the birds’ population, with Margaret Gaughan, a farmer participating in the project, in Belmullet, Ireland.",
			"copyright": "Paulo Nunes dos Santos for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/07/26/world/26Ireland-corncrake1/26Ireland-corncrake1-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "John Carey, the director of Corncrake Life, a conservation effort created to increase the birds’ population, with Margaret Gaughan, a farmer participating in the project, in Belmullet, Ireland.",
			"copyright": "Paulo Nunes dos Santos for The New York Times"
		}],
		"short_url": "https://nyti.ms/3JuuxRW"
	}, {
		"section": "world",
		"subsection": "asia",
		"title": "Welcomed by Taiwan, Pelosi Leaves Rising Tensions With China in Her Wake",
		"abstract": "In a high-stakes visit to Taiwan, Ms. Pelosi offered assurances of American support. Taiwan now faces the prospect of Chinese military drills that could violate what it says are its territorial waters.",
		"url": "https://www.nytimes.com/2022/08/03/world/asia/pelosi-taiwan-china.html",
		"uri": "nyt://article/7dc06789-4c75-5b49-ba9d-839bb4d9dc1b",
		"byline": "By Paul Mozur, Amy Chang Chien, John Liu and Chris Buckley",
		"item_type": "Article",
		"updated_date": "2022-08-04T10:54:45-04:00",
		"created_date": "2022-08-03T17:08:48-04:00",
		"published_date": "2022-08-03T17:08:48-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["United States International Relations", "International Relations", "Defense and Military Forces", "Democracy (Theory and Philosophy)"],
		"org_facet": ["House of Representatives"],
		"per_facet": ["Pelosi, Nancy"],
		"geo_facet": ["China", "Taiwan"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/09/02/world/03taiwan-pelosi1/03taiwan-pelosi1-superJumbo-v3.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Speaker Nancy Pelosi visiting Taiwan’s legislature in Taipei on Wednesday.",
			"copyright": "Ann Wang/Reuters"
		}, {
			"url": "https://static01.nyt.com/images/2022/09/02/world/03taiwan-pelosi1/03taiwan-pelosi1-threeByTwoSmallAt2X-v3.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Speaker Nancy Pelosi visiting Taiwan’s legislature in Taipei on Wednesday.",
			"copyright": "Ann Wang/Reuters"
		}, {
			"url": "https://static01.nyt.com/images/2022/09/02/world/03taiwan-pelosi1/03taiwan-pelosi1-thumbLarge-v3.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Speaker Nancy Pelosi visiting Taiwan’s legislature in Taipei on Wednesday.",
			"copyright": "Ann Wang/Reuters"
		}],
		"short_url": "https://nyti.ms/3zy9Z6j"
	}, {
		"section": "world",
		"subsection": "australia",
		"title": "Long a Climate Straggler, Australia Advances a Major Bill to Cut Emissions",
		"abstract": "Experts said the pledge to reduce emissions by at least 43 percent from 2005 levels by 2030 was both a leap forward and a first step.",
		"url": "https://www.nytimes.com/2022/08/04/world/australia/climate-bill.html",
		"uri": "nyt://article/6dc948f9-fb4a-5e34-ad12-9872d5683cca",
		"byline": "By Damien Cave",
		"item_type": "Article",
		"updated_date": "2022-08-04T22:10:27-04:00",
		"created_date": "2022-08-04T03:37:22-04:00",
		"published_date": "2022-08-04T03:37:22-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Greenhouse Gas Emissions", "Law and Legislation", "Global Warming"],
		"org_facet": [],
		"per_facet": ["Albanese, Anthony (1963- )"],
		"geo_facet": ["Australia"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/world/04oz-climate/merlin_198944100_2fd945e4-932d-49bc-a801-7cb7e7ae478e-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Australia is one of the most vulnerable countries to the ravages of climate change.",
			"copyright": "Matthew Abbott for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04oz-climate/merlin_198944100_2fd945e4-932d-49bc-a801-7cb7e7ae478e-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Australia is one of the most vulnerable countries to the ravages of climate change.",
			"copyright": "Matthew Abbott for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04oz-climate/merlin_198944100_2fd945e4-932d-49bc-a801-7cb7e7ae478e-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Australia is one of the most vulnerable countries to the ravages of climate change.",
			"copyright": "Matthew Abbott for The New York Times"
		}],
		"short_url": "https://nyti.ms/3cSZBhV"
	}, {
		"section": "world",
		"subsection": "americas",
		"title": "The Illegal Airstrips Bringing Toxic Mining to Brazil’s Indigenous Land",
		"abstract": "The Times identified hundreds of airstrips that bring criminal mining operations to the most remote corners of the Amazon.",
		"url": "https://www.nytimes.com/interactive/2022/08/02/world/americas/brazil-airstrips-illegal-mining.html",
		"uri": "nyt://interactive/6d42e317-c59b-526f-9f23-6bc773c43f2a",
		"byline": "By Manuela Andreoni, Blacki Migliozzi, Pablo Robles and Denise Lu",
		"item_type": "Interactive",
		"updated_date": "2022-08-03T19:26:26-04:00",
		"created_date": "2022-08-02T05:00:25-04:00",
		"published_date": "2022-08-02T05:00:25-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Mines and Mining", "Gold"],
		"org_facet": [],
		"per_facet": [],
		"geo_facet": ["Brazil", "Amazon Jungle"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/01/world/brazil-airstrips-illegal-mining-promo/brazil-airstrips-illegal-mining-promo-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1333,
			"width": 2000,
			"type": "image",
			"subtype": "photo",
			"caption": "",
			"copyright": "Victor Moriyama for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/01/world/brazil-airstrips-illegal-mining-promo/brazil-airstrips-illegal-mining-promo-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "",
			"copyright": "Victor Moriyama for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/01/world/brazil-airstrips-illegal-mining-promo/brazil-airstrips-illegal-mining-promo-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "",
			"copyright": "Victor Moriyama for The New York Times"
		}],
		"short_url": "https://nyti.ms/3cTAUC5"
	}, {
		"section": "business",
		"subsection": "economy",
		"title": "When Home Is a Ferry Ship: An Influx From Ukraine Strains Europe",
		"abstract": "Millions have fled Russia’s invasion, but where housing is expensive and scarce, countries like Estonia are paying shipping firms to offer refugees safe but tight quarters.",
		"url": "https://www.nytimes.com/2022/08/04/business/economy/ukraine-refugees-estonia.html",
		"uri": "nyt://article/1acbdeb0-6955-5ad5-8904-7917709bdfc8",
		"byline": "By Patricia Cohen",
		"item_type": "Article",
		"updated_date": "2022-08-04T16:09:28-04:00",
		"created_date": "2022-08-04T00:01:18-04:00",
		"published_date": "2022-08-04T00:01:18-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Russian Invasion of Ukraine (2022)", "Refugees and Displaced Persons", "Ships and Shipping"],
		"org_facet": [],
		"per_facet": [],
		"geo_facet": ["Ukraine", "Europe", "Russia", "Estonia", "Tallinn (Estonia)"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/02/business/00refugee-ship-1/merlin_210940392_b5b93186-3980-440d-a0aa-81264f5265b4-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Lunch time aboard the Isabelle cruise ship, which temporary houses 1,900 Ukrainians.",
			"copyright": "Marta Giaccone for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/02/business/00refugee-ship-1/merlin_210940392_b5b93186-3980-440d-a0aa-81264f5265b4-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Lunch time aboard the Isabelle cruise ship, which temporary houses 1,900 Ukrainians.",
			"copyright": "Marta Giaccone for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/02/business/00refugee-ship-1/00refugee-ship-1-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Lunch time aboard the Isabelle cruise ship, which temporary houses 1,900 Ukrainians.",
			"copyright": "Marta Giaccone for The New York Times"
		}],
		"short_url": "https://nyti.ms/3JrnREc"
	}, {
		"section": "briefing",
		"subsection": "",
		"title": "Coal vs. Wall Street",
		"abstract": "Republican state officials have found a new way to push back against “woke capitalism”— by punishing companies that distance themselves from fossil fuels.",
		"url": "https://www.nytimes.com/2022/08/05/briefing/climate-change-republicans.html",
		"uri": "nyt://article/65b9cd3f-3bb4-5df9-a0ae-d5eaaef6419e",
		"byline": "By David Leonhardt",
		"item_type": "Article",
		"updated_date": "2022-08-05T06:28:39-04:00",
		"created_date": "2022-08-05T06:28:39-04:00",
		"published_date": "2022-08-05T06:28:39-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["internal-storyline-no", "Greenhouse Gas Emissions", "United States Politics and Government"],
		"org_facet": ["Democratic Party", "Republican Party"],
		"per_facet": [],
		"geo_facet": [],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/05/multimedia/05-THE-MORNING-NL-promo/05-THE-MORNING-NL-Blackrock1-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Five major financial institutions, including BlackRock, were barred from doing business with West Virginia because the companies were distancing themselves from the coal industry.",
			"copyright": "Hiroko Masuike/The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/05/multimedia/05-THE-MORNING-NL-promo/05-THE-MORNING-NL-Blackrock1-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Five major financial institutions, including BlackRock, were barred from doing business with West Virginia because the companies were distancing themselves from the coal industry.",
			"copyright": "Hiroko Masuike/The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/05/multimedia/05-THE-MORNING-NL-promo/05-THE-MORNING-NL-Blackrock1-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Five major financial institutions, including BlackRock, were barred from doing business with West Virginia because the companies were distancing themselves from the coal industry.",
			"copyright": "Hiroko Masuike/The New York Times"
		}],
		"short_url": "https://nyti.ms/3zxKr9y"
	}, {
		"section": "world",
		"subsection": "asia",
		"title": "U.S. Seeks to Reassure Asian Allies as China’s Military Grows Bolder",
		"abstract": "The Biden administration says its commitment to the region has only deepened, but critics say the tensions over Taiwan show that Washington needs stronger military and economic strategies.",
		"url": "https://www.nytimes.com/2022/08/05/world/asia/taiwan-china-united-states-allies.html",
		"uri": "nyt://article/40ab24bd-83dc-5f5b-8b88-ed9e0b0bc5f4",
		"byline": "By Edward Wong and Damien Cave",
		"item_type": "Article",
		"updated_date": "2022-08-05T06:45:08-04:00",
		"created_date": "2022-08-05T05:57:56-04:00",
		"published_date": "2022-08-05T05:57:56-04:00",
		"material_type_facet": "",
		"kicker": "news analysis",
		"des_facet": ["International Relations", "United States International Relations", "Politics and Government", "Defense and Military Forces", "Territorial Disputes"],
		"org_facet": ["Assn of Southeast Asian Nations"],
		"per_facet": ["Pelosi, Nancy", "Wang Yi"],
		"geo_facet": ["Cambodia", "China"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/05/world/05taiwan-region1/merlin_211030920_5737c043-aba0-4bbe-bfb5-96dad721b81f-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Secretary of State Antony J. Blinken with the foreign ministers of Singapore and Vietnam during a meeting of the Association of Southeast Asian Nations in Phnom Penh, Cambodia, on Thursday. Mr. Blinken promised that the United States would stand by its allies.",
			"copyright": "Pool photo by Andrew Harnik"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/05/world/05taiwan-region1/merlin_211030920_5737c043-aba0-4bbe-bfb5-96dad721b81f-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Secretary of State Antony J. Blinken with the foreign ministers of Singapore and Vietnam during a meeting of the Association of Southeast Asian Nations in Phnom Penh, Cambodia, on Thursday. Mr. Blinken promised that the United States would stand by its allies.",
			"copyright": "Pool photo by Andrew Harnik"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/05/world/05taiwan-region1/05taiwan-region1-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Secretary of State Antony J. Blinken with the foreign ministers of Singapore and Vietnam during a meeting of the Association of Southeast Asian Nations in Phnom Penh, Cambodia, on Thursday. Mr. Blinken promised that the United States would stand by its allies.",
			"copyright": "Pool photo by Andrew Harnik"
		}],
		"short_url": "https://nyti.ms/3Q0uKi1"
	}, {
		"section": "world",
		"subsection": "asia",
		"title": "Fight or Surrender: Taiwan’s Generational Divide on China’s Threats",
		"abstract": "In areas close to the military drills, younger Taiwanese worried about the future, while older residents looked back to a harsher past to find hope.",
		"url": "https://www.nytimes.com/2022/08/05/world/asia/taiwan-response-china.html",
		"uri": "nyt://article/23c2978c-e12e-5eb1-adbc-6c1e28d7b458",
		"byline": "By Amy Chang Chien, John Liu and Paul Mozur",
		"item_type": "Article",
		"updated_date": "2022-08-05T06:46:32-04:00",
		"created_date": "2022-08-05T05:55:27-04:00",
		"published_date": "2022-08-05T05:55:27-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["International Relations", "Defense and Military Forces"],
		"org_facet": [],
		"per_facet": ["Taiwan Strait"],
		"geo_facet": ["China", "Taiwan"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/05/world/05-Taiwan-Threat-beach3/05-Taiwan-Threat-beach3-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1366,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Volunteers cleaned up a beach on the Matsu Islands on Thursday as Taiwanese troops loaded artillery shells onto a boat. Life there has proceeded mostly as normal during China’s recent military drills.",
			"copyright": "An Rong Xu for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/05/world/05-Taiwan-Threat-beach3/05-Taiwan-Threat-beach3-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Volunteers cleaned up a beach on the Matsu Islands on Thursday as Taiwanese troops loaded artillery shells onto a boat. Life there has proceeded mostly as normal during China’s recent military drills.",
			"copyright": "An Rong Xu for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/05/world/05-Taiwan-Threat-beach3/05-Taiwan-Threat-beach3-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Volunteers cleaned up a beach on the Matsu Islands on Thursday as Taiwanese troops loaded artillery shells onto a boat. Life there has proceeded mostly as normal during China’s recent military drills.",
			"copyright": "An Rong Xu for The New York Times"
		}],
		"short_url": "https://nyti.ms/3Q519Ec"
	}, {
		"section": "science",
		"subsection": "",
		"title": "The Mysterious Dance of the Cricket Embryos",
		"abstract": "A team of biologists and mathematicians studied hours of video to learn how insects take shape in the egg. The secret is geometry.",
		"url": "https://www.nytimes.com/2022/08/05/science/cricket-embryos-biology-development.html",
		"uri": "nyt://article/9cfd6db4-4f1e-54a6-813f-4a4270b24386",
		"byline": "By Siobhan Roberts",
		"item_type": "Article",
		"updated_date": "2022-08-05T05:00:45-04:00",
		"created_date": "2022-08-05T05:00:45-04:00",
		"published_date": "2022-08-05T05:00:45-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Fruit Flies", "Biology and Biochemistry", "Laboratories and Scientific Equipment", "Mathematics", "Insects", "Crickets", "Evolution (Biology)", "Microbiology", "your-feed-science", "your-feed-animals", "Anatomy and Physiology"],
		"org_facet": [],
		"per_facet": ["Cassandra Extavour", "Seth Donoughe", "Stefano Di Talia", "Taro Nakamura", "Christopher Rycroft", "Jordan Hoffmann"],
		"geo_facet": [],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/science/00SCI-CRICKETS-grid2/00SCI-CRICKETS-grid2-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 2048,
			"width": 1367,
			"type": "image",
			"subtype": "photo",
			"caption": "Micrographs of various portions of cricket embryos during development. Images like these are used in studying how embryonic cells divide, multiply and collectively give rise to functioning body parts.",
			"copyright": "Cassandra Extavour"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/science/00SCI-CRICKETS-grid2/00SCI-CRICKETS-grid2-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Micrographs of various portions of cricket embryos during development. Images like these are used in studying how embryonic cells divide, multiply and collectively give rise to functioning body parts.",
			"copyright": "Cassandra Extavour"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/science/00SCI-CRICKETS-grid2/00SCI-CRICKETS-grid2-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Micrographs of various portions of cricket embryos during development. Images like these are used in studying how embryonic cells divide, multiply and collectively give rise to functioning body parts.",
			"copyright": "Cassandra Extavour"
		}],
		"short_url": "https://nyti.ms/3oSvryh"
	}, {
		"section": "world",
		"subsection": "asia",
		"title": "‘Captain Condom’ Turned the Tide in Thailand’s War on AIDS and Overpopulation",
		"abstract": "At a time when most Thais avoided discussing safe sex and family planning, Mechai Viravaidya promoted condom use with spectacle and humor, saving millions of lives.",
		"url": "https://www.nytimes.com/2022/08/05/world/asia/thailand-aids-overpopulation-mechai.html",
		"uri": "nyt://article/2a5740e5-9d60-5e2f-800d-d2a8cdc05708",
		"byline": "By Seth Mydans",
		"item_type": "Article",
		"updated_date": "2022-08-05T05:00:35-04:00",
		"created_date": "2022-08-05T05:00:35-04:00",
		"published_date": "2022-08-05T05:00:35-04:00",
		"material_type_facet": "",
		"kicker": "The Saturday Profile",
		"des_facet": ["Condoms", "Rural Areas", "Population", "Acquired Immune Deficiency Syndrome", "Birth Control and Family Planning", "Vasectomy"],
		"org_facet": ["United Nations"],
		"per_facet": ["Mechai Viravaidya"],
		"geo_facet": ["Thailand", "Bangkok (Thailand)"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/06/world/05Thailand-CaptainCondom-Profile1a/05Thailand-CaptainCondom-Profile1a-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Concerned that Thailand’s population was growing at an unsustainable pace, Mechai Viravaidya began promoting condom usage in the early 1970s, when few were willing to broach the subject.",
			"copyright": "Lauren DeCicca for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/06/world/05Thailand-CaptainCondom-Profile1a/05Thailand-CaptainCondom-Profile1a-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Concerned that Thailand’s population was growing at an unsustainable pace, Mechai Viravaidya began promoting condom usage in the early 1970s, when few were willing to broach the subject.",
			"copyright": "Lauren DeCicca for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/06/world/05Thailand-CaptainCondom-Profile1a/05Thailand-CaptainCondom-Profile1a-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Concerned that Thailand’s population was growing at an unsustainable pace, Mechai Viravaidya began promoting condom usage in the early 1970s, when few were willing to broach the subject.",
			"copyright": "Lauren DeCicca for The New York Times"
		}],
		"short_url": "https://nyti.ms/3d92ewk"
	}, {
		"section": "magazine",
		"subsection": "",
		"title": "Who Killed Tair Rada? Inside Israel’s True Crime Obsession",
		"abstract": "A TV documentary upended a murder case and captivated the nation. But its sensational theories might also be distorting justice.",
		"url": "https://www.nytimes.com/2022/08/05/magazine/shadow-of-truth-tair-rada.html",
		"uri": "nyt://article/3d7474aa-0aad-5104-9191-0ebfa2139d57",
		"byline": "By Ruth Margalit",
		"item_type": "Article",
		"updated_date": "2022-08-05T05:00:32-04:00",
		"created_date": "2022-08-05T05:00:32-04:00",
		"published_date": "2022-08-05T05:00:32-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Forensic Science", "Documentary Films and Programs", "Murders, Attempted Murders and Homicides", "Television"],
		"org_facet": ["Facebook Inc"],
		"per_facet": [],
		"geo_facet": ["Israel"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/07/magazine/07Mag-Israeli-01-copy/07Mag-Israeli-01-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1744,
			"width": 1454,
			"type": "image",
			"subtype": "photo",
			"caption": "",
			"copyright": "Photo illustration by Mike McQuade"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/07/magazine/07Mag-Israeli-01-copy/07Mag-Israeli-01-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "",
			"copyright": "Photo illustration by Mike McQuade"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/07/magazine/07Mag-Israeli-01-copy/07Mag-Israeli-01-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "",
			"copyright": "Photo illustration by Mike McQuade"
		}],
		"short_url": "https://nyti.ms/3bxDOfv"
	}, {
		"section": "climate",
		"subsection": "",
		"title": "How Republicans Are ‘Weaponizing’ Public Office Against Climate Action",
		"abstract": "A Times investigation revealed a coordinated effort by state treasurers to use government muscle and public funds to punish companies trying to reduce greenhouse gases.",
		"url": "https://www.nytimes.com/2022/08/05/climate/republican-treasurers-climate-change.html",
		"uri": "nyt://article/4dd6c852-00e7-5bbc-8d86-2e160905ca8c",
		"byline": "By David Gelles",
		"item_type": "Article",
		"updated_date": "2022-08-05T06:18:34-04:00",
		"created_date": "2022-08-05T03:00:11-04:00",
		"published_date": "2022-08-05T03:00:11-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Global Warming", "Greenhouse Gas Emissions", "Banking and Financial Institutions", "Conservatism (US Politics)", "Lobbying and Lobbyists", "United States Politics and Government", "States (US)", "Oil (Petroleum) and Gasoline", "Pensions and Retirement Plans", "Boycotts", "Coal", "United States Economy", "Corporate Social Responsibility"],
		"org_facet": ["State Financial Officers Foundation", "Republican Party", "American Legislative Exchange Council", "BlackRock Inc", "Heartland Institute", "Heritage Foundation"],
		"per_facet": ["Fink, Laurence D"],
		"geo_facet": ["West Virginia"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/03/climate/00cli-treasurers1/00cli-treasurers1-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1536,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Riley Moore, the West Virginia treasurer, announced last week that several major bank would be barred from government contracts with his state.",
			"copyright": "Kristian Thacker for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/03/climate/00cli-treasurers1/00cli-treasurers1-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Riley Moore, the West Virginia treasurer, announced last week that several major bank would be barred from government contracts with his state.",
			"copyright": "Kristian Thacker for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/03/climate/00cli-treasurers1/00cli-treasurers1-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Riley Moore, the West Virginia treasurer, announced last week that several major bank would be barred from government contracts with his state.",
			"copyright": "Kristian Thacker for The New York Times"
		}],
		"short_url": "https://nyti.ms/3oWUaBC"
	}, {
		"section": "world",
		"subsection": "europe",
		"title": "Putin and Erdogan, both partners and foes, are set to talk in Sochi, Russia.",
		"abstract": "The Turkish and Russian leaders are meeting for the second time in less than three weeks.",
		"url": "https://www.nytimes.com/2022/08/05/world/europe/putin-erdogan.html",
		"uri": "nyt://article/5f8512cc-071e-5e9f-9b00-f39633cb0bc1",
		"byline": "By Neil MacFarquhar",
		"item_type": "Article",
		"updated_date": "2022-08-05T01:09:29-04:00",
		"created_date": "2022-08-05T01:09:29-04:00",
		"published_date": "2022-08-05T01:09:29-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["International Relations", "Russian Invasion of Ukraine (2022)", "War and Armed Conflicts"],
		"org_facet": [],
		"per_facet": ["Putin, Vladimir V", "Erdogan, Recep Tayyip"],
		"geo_facet": ["Turkey", "Russia", "Ukraine"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04ukraine-briefing-putin-erdogan-01/04ukraine-briefing-putin-erdogan-01-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1366,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "President Recep Tayyip Erdogan of Turkey will meet Friday with President Vladimir V. Putin of Russia. ",
			"copyright": "Burhan Ozbilici/Associated Press"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04ukraine-briefing-putin-erdogan-01/04ukraine-briefing-putin-erdogan-01-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "President Recep Tayyip Erdogan of Turkey will meet Friday with President Vladimir V. Putin of Russia. ",
			"copyright": "Burhan Ozbilici/Associated Press"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04ukraine-briefing-putin-erdogan-01/04ukraine-briefing-putin-erdogan-01-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "President Recep Tayyip Erdogan of Turkey will meet Friday with President Vladimir V. Putin of Russia. ",
			"copyright": "Burhan Ozbilici/Associated Press"
		}],
		"short_url": "https://nyti.ms/3JxLD1k"
	}, {
		"section": "world",
		"subsection": "",
		"title": "Driven by its first lady, Ukraine raises $5.4 million for off-road ambulances.",
		"abstract": "Olena Zelenska has recently become more visible in advocating for humanitarian causes.",
		"url": "https://www.nytimes.com/2022/08/05/world/olena-zelenska-ukraine-ambulances.html",
		"uri": "nyt://article/2ec64d92-7304-5d90-9653-ab8bd4974733",
		"byline": "By Carly Olson",
		"item_type": "Article",
		"updated_date": "2022-08-05T01:09:26-04:00",
		"created_date": "2022-08-05T01:09:26-04:00",
		"published_date": "2022-08-05T01:09:26-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Russian Invasion of Ukraine (2022)", "War and Armed Conflicts"],
		"org_facet": [],
		"per_facet": ["Zelenska, Olena", "Zelensky, Volodymyr"],
		"geo_facet": [],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/07/31/multimedia/31-ukraine-briefing-ambulance/31-ukraine-briefing-ambulance-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1366,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "A wounded Ukrainian soldier being transferred from the front lines near Izium, eastern Ukraine, to a hospital in the city of Kramatorsk in June.",
			"copyright": "Ivor Prickett for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/07/31/multimedia/31-ukraine-briefing-ambulance/31-ukraine-briefing-ambulance-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "A wounded Ukrainian soldier being transferred from the front lines near Izium, eastern Ukraine, to a hospital in the city of Kramatorsk in June.",
			"copyright": "Ivor Prickett for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/07/31/multimedia/31-ukraine-briefing-ambulance/31-ukraine-briefing-ambulance-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "A wounded Ukrainian soldier being transferred from the front lines near Izium, eastern Ukraine, to a hospital in the city of Kramatorsk in June.",
			"copyright": "Ivor Prickett for The New York Times"
		}],
		"short_url": "https://nyti.ms/3JuXP2I"
	}, {
		"section": "world",
		"subsection": "asia",
		"title": "China Sends Ships and Planes Toward Taiwan, Despite Rising Criticism",
		"abstract": "Japan’s leader called for an immediate halt to the military drills, now in their second day. Speaker Nancy Pelosi said China “will not isolate Taiwan.”",
		"url": "https://www.nytimes.com/2022/08/04/world/asia/taiwan-china-military-drills.html",
		"uri": "nyt://article/71ff93df-fac9-53be-8afb-6ef49a14455b",
		"byline": "By Jane Perlez and Mike Ives",
		"item_type": "Article",
		"updated_date": "2022-08-05T05:05:04-04:00",
		"created_date": "2022-08-04T23:49:26-04:00",
		"published_date": "2022-08-04T23:49:26-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Defense and Military Forces", "Territorial Disputes"],
		"org_facet": ["People's Liberation Army (China)", "United States Navy"],
		"per_facet": ["Pelosi, Nancy", "Taiwan Strait"],
		"geo_facet": ["Taiwan", "China", "Japan"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/09/04/world/05taiwan-drills-lede/04taiwan-lede1-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Taiwanese navy ships in Keelung, Taiwan, on Friday. Taiwan’s defense ministry said Chinese ships and planes crossed the informal median line in the Taiwan Strait on Friday. ",
			"copyright": "Lam Yik Fei for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/09/04/world/05taiwan-drills-lede/04taiwan-lede1-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Taiwanese navy ships in Keelung, Taiwan, on Friday. Taiwan’s defense ministry said Chinese ships and planes crossed the informal median line in the Taiwan Strait on Friday. ",
			"copyright": "Lam Yik Fei for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/09/04/world/05taiwan-drills-lede/04taiwan-lede1-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Taiwanese navy ships in Keelung, Taiwan, on Friday. Taiwan’s defense ministry said Chinese ships and planes crossed the informal median line in the Taiwan Strait on Friday. ",
			"copyright": "Lam Yik Fei for The New York Times"
		}],
		"short_url": "https://nyti.ms/3Q3Nygt"
	}, {
		"section": "world",
		"subsection": "europe",
		"title": "Three more ships carrying grain depart from Ukraine.",
		"abstract": "The ships are carrying a total of about 64,000 tons of corn from Ukraine’s desperately needed stores.",
		"url": "https://www.nytimes.com/2022/08/04/world/europe/ukraine-grain-ships.html",
		"uri": "nyt://article/a83b1ceb-62b6-52ee-8b0c-0f31f5daf82a",
		"byline": "By Farnaz Fassihi and Sophie Downes",
		"item_type": "Article",
		"updated_date": "2022-08-05T05:26:02-04:00",
		"created_date": "2022-08-04T19:30:16-04:00",
		"published_date": "2022-08-04T19:30:16-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Ships and Shipping", "Russian Invasion of Ukraine (2022)", "Grain", "Shortages", "Food"],
		"org_facet": ["United Nations"],
		"per_facet": [],
		"geo_facet": ["Black Sea", "Ukraine", "Istanbul (Turkey)", "Russia"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04ukraine-briefing-grain-ships/04ukraine-briefing-grain-ships-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "The Navi-Star waiting to depart with its cargo of grain at the Port of Odesa in Ukraine last week.",
			"copyright": "David Goldman/Associated Press"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04ukraine-briefing-grain-ships/04ukraine-briefing-grain-ships-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "The Navi-Star waiting to depart with its cargo of grain at the Port of Odesa in Ukraine last week.",
			"copyright": "David Goldman/Associated Press"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04ukraine-briefing-grain-ships/04ukraine-briefing-grain-ships-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "The Navi-Star waiting to depart with its cargo of grain at the Port of Odesa in Ukraine last week.",
			"copyright": "David Goldman/Associated Press"
		}],
		"short_url": "https://nyti.ms/3Su8qyW"
	}, {
		"section": "briefing",
		"subsection": "",
		"title": "Your Friday Briefing: Russia Sentences Brittney Griner to 9 Years",
		"abstract": "Also, China’s military tests threaten Taiwan and Australia advances a major climate bill.",
		"url": "https://www.nytimes.com/2022/08/04/briefing/brittney-griner-russia-sentence-china-taiwan.html",
		"uri": "nyt://article/b7817547-3d60-58ab-b738-62ed6f628751",
		"byline": "By Matthew Cullen",
		"item_type": "Article",
		"updated_date": "2022-08-04T19:17:05-04:00",
		"created_date": "2022-08-04T17:00:21-04:00",
		"published_date": "2022-08-04T17:00:21-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": [],
		"org_facet": [],
		"per_facet": [],
		"geo_facet": [],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/05/multimedia/05ambriefing-asia-nl-aug-PROMO/05ambriefing-asia-nl-aug-griner-superJumbo-v3.jpg",
			"format": "Super Jumbo",
			"height": 1364,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "U.S. basketball player Brittney Griner stood in a defendants' cage in Khimki, outside Moscow, on August 4, 2022.",
			"copyright": "Evgenia Novozhenina/Reuters"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/05/multimedia/05ambriefing-asia-nl-aug-PROMO/05ambriefing-asia-nl-aug-griner-threeByTwoSmallAt2X-v3.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "U.S. basketball player Brittney Griner stood in a defendants' cage in Khimki, outside Moscow, on August 4, 2022.",
			"copyright": "Evgenia Novozhenina/Reuters"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/05/multimedia/05ambriefing-asia-nl-aug-PROMO/05ambriefing-asia-nl-aug-griner-thumbLarge-v3.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "U.S. basketball player Brittney Griner stood in a defendants' cage in Khimki, outside Moscow, on August 4, 2022.",
			"copyright": "Evgenia Novozhenina/Reuters"
		}],
		"short_url": "https://nyti.ms/3zBaJrl"
	}, {
		"section": "world",
		"subsection": "europe",
		"title": "Russian Court Sentences Griner to 9 Years, Raising Pressure on Biden",
		"abstract": "Amid the hostility over the war in Ukraine, a court imposed nearly the maximum possible sentence on the American basketball star Brittney Griner, intensifying calls to win her release.",
		"url": "https://www.nytimes.com/2022/08/04/world/europe/russia-brittney-griner-sentence.html",
		"uri": "nyt://article/4a07251e-32d3-568b-9b98-6e56e0516ee6",
		"byline": "By Ivan Nechepurenko and Richard Pérez-Peña",
		"item_type": "Article",
		"updated_date": "2022-08-05T06:07:20-04:00",
		"created_date": "2022-08-04T16:59:39-04:00",
		"published_date": "2022-08-04T16:59:39-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Political Prisoners", "United States International Relations", "Decisions and Verdicts", "Russian Invasion of Ukraine (2022)"],
		"org_facet": ["Women's National Basketball Assn", "UMMC Yekaterinburg", "Phoenix Mercury"],
		"per_facet": ["Griner, Brittney", "Biden, Joseph R Jr", "Bout, Viktor", "Whelan, Paul N"],
		"geo_facet": ["Russia"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/world/04griner-1/merlin_211040886_243958fe-c0bf-4e57-88a7-be8bdfe799bc-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1365,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Brittney Griner leaving the courtroom before the court's final decision in Khimki outside Moscow on Thursday.",
			"copyright": "Pool photo by Kirill Kudryavtsev"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04griner-1/merlin_211040886_243958fe-c0bf-4e57-88a7-be8bdfe799bc-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Brittney Griner leaving the courtroom before the court's final decision in Khimki outside Moscow on Thursday.",
			"copyright": "Pool photo by Kirill Kudryavtsev"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04griner-1/merlin_211040886_243958fe-c0bf-4e57-88a7-be8bdfe799bc-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Brittney Griner leaving the courtroom before the court's final decision in Khimki outside Moscow on Thursday.",
			"copyright": "Pool photo by Kirill Kudryavtsev"
		}],
		"short_url": "https://nyti.ms/3BLPA0q"
	}, {
		"section": "world",
		"subsection": "australia",
		"title": "A Large Object Landed on His Sheep Farm. It Came From Space.",
		"abstract": "“It’s not something you see every day on a sheep farm,” a farmer said of the pieces of debris that wound up in rural Australia. They are thought to be from a SpaceX spacecraft.",
		"url": "https://www.nytimes.com/2022/08/04/world/australia/spacex-debris-australia.html",
		"uri": "nyt://article/da651fb6-3c95-5b77-817f-5dc05ad356f0",
		"byline": "By Mike Ives and Jenny Gross",
		"item_type": "Article",
		"updated_date": "2022-08-04T17:28:46-04:00",
		"created_date": "2022-08-04T16:55:54-04:00",
		"published_date": "2022-08-04T16:55:54-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Space and Astronomy", "Private Spaceflight", "Rocket Science and Propulsion"],
		"org_facet": ["Defense Department", "Federal Aviation Administration", "National Aeronautics and Space Administration", "Space Exploration Technologies Corp"],
		"per_facet": ["Musk, Elon"],
		"geo_facet": ["Australia"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04xp-spacedebris-01/04xp-spacedebris-01-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1364,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "A sheepherder in Dalgety, Australia, stumbled upon a tall piece of space junk, said to be debris from the SpaceX Crew-1 spacecraft.",
			"copyright": "Brad Tucker via Reuters"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04xp-spacedebris-01/04xp-spacedebris-01-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "A sheepherder in Dalgety, Australia, stumbled upon a tall piece of space junk, said to be debris from the SpaceX Crew-1 spacecraft.",
			"copyright": "Brad Tucker via Reuters"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04xp-spacedebris-01/04xp-spacedebris-01-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "A sheepherder in Dalgety, Australia, stumbled upon a tall piece of space junk, said to be debris from the SpaceX Crew-1 spacecraft.",
			"copyright": "Brad Tucker via Reuters"
		}],
		"short_url": "https://nyti.ms/3zAdkC8"
	}, {
		"section": "world",
		"subsection": "europe",
		"title": "Three Tourists Are Injured Near Volcanic Eruption in Iceland",
		"abstract": "The injuries were not serious, but they underscored the risks facing tourists who hike to the Fagradalsfjall volcano in southwest Iceland, officials said.",
		"url": "https://www.nytimes.com/2022/08/04/world/europe/fagradalsfjall-iceland-volcano-tourists.html",
		"uri": "nyt://article/b6050712-ce3a-597c-92f3-5415e82ec502",
		"byline": "By Michael Levenson",
		"item_type": "Article",
		"updated_date": "2022-08-04T22:55:09-04:00",
		"created_date": "2022-08-04T16:53:13-04:00",
		"published_date": "2022-08-04T16:53:13-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Volcanoes", "Airlines and Airplanes", "Travel and Vacations"],
		"org_facet": ["Icelandair"],
		"per_facet": [],
		"geo_facet": ["Fagradalsfjall (Iceland)", "Iceland"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04xp-volcano-1/04xp-volcano-1-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1367,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "The Fagradalsfjall volcano has been drawing tourists, despite warnings from the government that the area is dangerous. ",
			"copyright": "Marco Di Marco/Associated Press"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04xp-volcano-1/04xp-volcano-1-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "The Fagradalsfjall volcano has been drawing tourists, despite warnings from the government that the area is dangerous. ",
			"copyright": "Marco Di Marco/Associated Press"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04xp-volcano-1/04xp-volcano-1-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "The Fagradalsfjall volcano has been drawing tourists, despite warnings from the government that the area is dangerous. ",
			"copyright": "Marco Di Marco/Associated Press"
		}],
		"short_url": "https://nyti.ms/3Qbw8ye"
	}, {
		"section": "world",
		"subsection": "canada",
		"title": "Hockey Canada to Be Investigated After Settling Sexual Assault Complaints",
		"abstract": "Canada’s governing body for hockey has come under increasing scrutiny after revelations that it has paid millions of dollars to settle sexual assault and abuse claims.",
		"url": "https://www.nytimes.com/2022/08/04/world/canada/hockey-canada-sex-complaints.html",
		"uri": "nyt://article/3c459532-da3f-517d-b948-e40c9e34a35d",
		"byline": "By Ian Austen",
		"item_type": "Article",
		"updated_date": "2022-08-04T16:48:11-04:00",
		"created_date": "2022-08-04T16:48:11-04:00",
		"published_date": "2022-08-04T16:48:11-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Sex Crimes", "Suits and Litigation (Civil)", "Hockey, Ice"],
		"org_facet": ["Canadian Hockey Assn"],
		"per_facet": [],
		"geo_facet": ["Canada"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/world/04canada-hockey/04canada-hockey-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1364,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "From left, Andrew Winton, a lawyer, Scott Smith, the president of Hockey Canada, and Brian Cairo, the group’s chief financial officer, appeared before a parliamentary committee looking into how Hockey Canada handled sexual assault allegations",
			"copyright": "Sean Kilpatrick/The Canadian Press, via Associated Press"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04canada-hockey/04canada-hockey-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "From left, Andrew Winton, a lawyer, Scott Smith, the president of Hockey Canada, and Brian Cairo, the group’s chief financial officer, appeared before a parliamentary committee looking into how Hockey Canada handled sexual assault allegations",
			"copyright": "Sean Kilpatrick/The Canadian Press, via Associated Press"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04canada-hockey/04canada-hockey-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "From left, Andrew Winton, a lawyer, Scott Smith, the president of Hockey Canada, and Brian Cairo, the group’s chief financial officer, appeared before a parliamentary committee looking into how Hockey Canada handled sexual assault allegations",
			"copyright": "Sean Kilpatrick/The Canadian Press, via Associated Press"
		}],
		"short_url": "https://nyti.ms/3oVSmZj"
	}, {
		"section": "world",
		"subsection": "europe",
		"title": "Griner is being sent to a Russian penal colony. What is that?",
		"abstract": "The penal colonies, many of them scattered across Siberia, are descendants of gulags and are characterized by brutality, overcrowding and harsh conditions.",
		"url": "https://www.nytimes.com/2022/08/04/world/europe/russia-penal-colony-brittney-griner.html",
		"uri": "nyt://article/78614bd9-968a-5e80-bfa4-c32800544d62",
		"byline": "By Ruth Maclean",
		"item_type": "Article",
		"updated_date": "2022-08-04T16:43:30-04:00",
		"created_date": "2022-08-04T16:43:30-04:00",
		"published_date": "2022-08-04T16:43:30-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Political Prisoners", "Prisons and Prisoners", "Propaganda"],
		"org_facet": [],
		"per_facet": ["Griner, Brittney"],
		"geo_facet": ["Russia"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04griner-blog-penal-colony-topart/04griner-blog-penal-colony-topart-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1366,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Penal colony IK-3, in Vladimir, Russia, one of the detention centers where opposition leader Aleksei Navalny has reportedly been held during his imprisonment.",
			"copyright": "Dimitar Dilkoff/Agence France-Presse — Getty Images"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04griner-blog-penal-colony-topart/04griner-blog-penal-colony-topart-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Penal colony IK-3, in Vladimir, Russia, one of the detention centers where opposition leader Aleksei Navalny has reportedly been held during his imprisonment.",
			"copyright": "Dimitar Dilkoff/Agence France-Presse — Getty Images"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04griner-blog-penal-colony-topart/04griner-blog-penal-colony-topart-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Penal colony IK-3, in Vladimir, Russia, one of the detention centers where opposition leader Aleksei Navalny has reportedly been held during his imprisonment.",
			"copyright": "Dimitar Dilkoff/Agence France-Presse — Getty Images"
		}],
		"short_url": "https://nyti.ms/3BIHupp"
	}, {
		"section": "health",
		"subsection": "",
		"title": "As Monkeypox Spreads, U.S. Declares a Health Emergency",
		"abstract": "The designation will free up emergency funds and lift some bureaucratic hurdles, but many experts fear containment may no longer be possible.",
		"url": "https://www.nytimes.com/2022/08/04/health/monkeypox-emergency-us.html",
		"uri": "nyt://article/ea052efa-aa17-553b-aad7-61440ad4195b",
		"byline": "By Sheryl Gay Stolberg and Apoorva Mandavilli",
		"item_type": "Article",
		"updated_date": "2022-08-04T22:50:25-04:00",
		"created_date": "2022-08-04T13:24:25-04:00",
		"published_date": "2022-08-04T13:24:25-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["your-feed-science", "Monkeypox", "Epidemics", "Vaccination and Immunization"],
		"org_facet": ["Health and Human Services Department", "World Health Organization"],
		"per_facet": [],
		"geo_facet": [],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/07/28/science/00monkeypox-emergency1/merlin_210617952_9c2daa52-78b8-45db-a76f-0c75bbde36ed-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1366,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "A monkeypox vaccination at a clinic on Fire Island in New York this month. As of Wednesday, the United States had recorded nearly 7,000 monkeypox cases.",
			"copyright": "Eduardo Munoz/Reuters"
		}, {
			"url": "https://static01.nyt.com/images/2022/07/28/science/00monkeypox-emergency1/00monkeypox-emergency1-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "A monkeypox vaccination at a clinic on Fire Island in New York this month. As of Wednesday, the United States had recorded nearly 7,000 monkeypox cases.",
			"copyright": "Eduardo Munoz/Reuters"
		}, {
			"url": "https://static01.nyt.com/images/2022/07/28/science/00monkeypox-emergency1/00monkeypox-emergency1-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "A monkeypox vaccination at a clinic on Fire Island in New York this month. As of Wednesday, the United States had recorded nearly 7,000 monkeypox cases.",
			"copyright": "Eduardo Munoz/Reuters"
		}],
		"short_url": "https://nyti.ms/3d6iK05"
	}, {
		"section": "world",
		"subsection": "",
		"title": "Who is Viktor Bout, the Russian arms dealer who could be involved in a prisoner trade for Griner?",
		"abstract": "The United States has proposed exchanging Brittney Griner and another American jailed in Russia for Mr. Bout, who was convicted in 2011 on charges including conspiring to kill American citizens.",
		"url": "https://www.nytimes.com/2022/08/04/world/viktor-bout-griner-prisoner-swap.html",
		"uri": "nyt://article/22cb0a01-3389-5dc6-bebd-76ba6c739d72",
		"byline": "By Valerie Hopkins and Alan Yuhas",
		"item_type": "Article",
		"updated_date": "2022-08-04T13:36:47-04:00",
		"created_date": "2022-08-04T12:51:36-04:00",
		"published_date": "2022-08-04T12:51:36-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": [],
		"org_facet": ["GRU (Russia)"],
		"per_facet": ["Bout, Viktor", "Griner, Brittney"],
		"geo_facet": [],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/world/04ukraine-briefing-bout-version/merlin_210896151_8b71ff8f-9c95-4b03-a98f-48d2aabb7548-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1524,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "The United States has proposed exchanging Viktor Bout, an imprisoned Russian arms dealer, for Brittney Griner and Paul Whelan, a former Marine.",
			"copyright": "Sukree Sukplang/Reuters"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04ukraine-briefing-bout-version/04ukraine-briefing-bout-version-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "The United States has proposed exchanging Viktor Bout, an imprisoned Russian arms dealer, for Brittney Griner and Paul Whelan, a former Marine.",
			"copyright": "Sukree Sukplang/Reuters"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04ukraine-briefing-bout-version/04ukraine-briefing-bout-version-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "The United States has proposed exchanging Viktor Bout, an imprisoned Russian arms dealer, for Brittney Griner and Paul Whelan, a former Marine.",
			"copyright": "Sukree Sukplang/Reuters"
		}],
		"short_url": "https://nyti.ms/3zE5CqK"
	}, {
		"section": "world",
		"subsection": "europe",
		"title": "‘I made an honest mistake,’ Griner tells the court.",
		"abstract": "Brittney Griner offered a glimpse of her personal story while testifying in a Russian court on Thursday.",
		"url": "https://www.nytimes.com/2022/08/04/world/europe/brittney-griner-trial-testimony.html",
		"uri": "nyt://article/2b762c78-824b-5cb8-8638-86a5e861349d",
		"byline": "By Ivan Nechepurenko",
		"item_type": "Article",
		"updated_date": "2022-08-04T14:58:33-04:00",
		"created_date": "2022-08-04T09:42:22-04:00",
		"published_date": "2022-08-04T09:42:22-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": [],
		"org_facet": [],
		"per_facet": [],
		"geo_facet": [],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/world/04ukraine-briefing-griner-testify/merlin_211032822_35e3fe3c-8247-4b17-a36f-e9780c2f939e-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1368,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "Brittney Griner speaking with her lawyers Maria Blagovolina, left, and Alexander Boykov in court on Thursday.",
			"copyright": "Pool photo by Evgenia Novozhenina"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04ukraine-briefing-griner-testify/merlin_211032822_35e3fe3c-8247-4b17-a36f-e9780c2f939e-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "Brittney Griner speaking with her lawyers Maria Blagovolina, left, and Alexander Boykov in court on Thursday.",
			"copyright": "Pool photo by Evgenia Novozhenina"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04ukraine-briefing-griner-testify/merlin_211032822_35e3fe3c-8247-4b17-a36f-e9780c2f939e-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "Brittney Griner speaking with her lawyers Maria Blagovolina, left, and Alexander Boykov in court on Thursday.",
			"copyright": "Pool photo by Evgenia Novozhenina"
		}],
		"short_url": "https://nyti.ms/3P0v8fo"
	}, {
		"section": "world",
		"subsection": "europe",
		"title": "Germany’s conservative leaders push for nuclear power to stay on as the country breaks from Russian fuels.",
		"abstract": "Nuclear power is contentious in Germany, but the country is also likely to be sharply affected by Europe’s efforts to wean itself off Russian fuel sources because of Moscow’s war in Ukraine.",
		"url": "https://www.nytimes.com/2022/08/04/world/europe/germany-nuclear-power-russia.html",
		"uri": "nyt://article/3dddebb9-c13d-5e17-ad34-cfaa122ac057",
		"byline": "By Erika Solomon",
		"item_type": "Article",
		"updated_date": "2022-08-04T09:31:06-04:00",
		"created_date": "2022-08-04T07:56:12-04:00",
		"published_date": "2022-08-04T07:56:12-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["Nuclear Energy", "International Relations", "Russian Invasion of Ukraine (2022)"],
		"org_facet": [],
		"per_facet": [],
		"geo_facet": ["Germany"],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/world/04ukraine-briefing-germany-nuclear/merlin_210940944_d49ea8f6-83da-4cb9-af8d-aee62b5f11db-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1536,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "The German village of Wattenbacherau, at the foot of the Isar 2 nuclear power plant, last week.",
			"copyright": "Laetitia Vancon for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04ukraine-briefing-germany-nuclear/04ukraine-briefing-germany-nuclear-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "The German village of Wattenbacherau, at the foot of the Isar 2 nuclear power plant, last week.",
			"copyright": "Laetitia Vancon for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/world/04ukraine-briefing-germany-nuclear/04ukraine-briefing-germany-nuclear-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "The German village of Wattenbacherau, at the foot of the Isar 2 nuclear power plant, last week.",
			"copyright": "Laetitia Vancon for The New York Times"
		}],
		"short_url": "https://nyti.ms/3SliYAJ"
	}, {
		"section": "briefing",
		"subsection": "",
		"title": "Defying the Supreme Court",
		"abstract": "The Kansas abortion vote and the congressional push on same-sex marriage show how progressives can confront the Supreme Court.",
		"url": "https://www.nytimes.com/2022/08/04/briefing/kansas-abortion-referendum-supreme-court-congress.html",
		"uri": "nyt://article/e160e996-5403-5307-998f-71844a16d1b1",
		"byline": "By David Leonhardt",
		"item_type": "Article",
		"updated_date": "2022-08-05T05:17:27-04:00",
		"created_date": "2022-08-04T06:30:00-04:00",
		"published_date": "2022-08-04T06:30:00-04:00",
		"material_type_facet": "",
		"kicker": "",
		"des_facet": ["internal-storyline-no", "Same-Sex Marriage, Civil Unions and Domestic Partnerships", "Decisions and Verdicts", "Elections", "States (US)"],
		"org_facet": [],
		"per_facet": [],
		"geo_facet": [],
		"multimedia": [{
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04-THE-MORNING-NL-promo/04-THE-MORNING-NL-top01-superJumbo.jpg",
			"format": "Super Jumbo",
			"height": 1366,
			"width": 2048,
			"type": "image",
			"subtype": "photo",
			"caption": "A view of the U.S. Capitol from the Supreme Court.",
			"copyright": "Stefani Reynolds for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04-THE-MORNING-NL-promo/04-THE-MORNING-NL-top01-threeByTwoSmallAt2X.jpg",
			"format": "threeByTwoSmallAt2X",
			"height": 400,
			"width": 600,
			"type": "image",
			"subtype": "photo",
			"caption": "A view of the U.S. Capitol from the Supreme Court.",
			"copyright": "Stefani Reynolds for The New York Times"
		}, {
			"url": "https://static01.nyt.com/images/2022/08/04/multimedia/04-THE-MORNING-NL-promo/04-THE-MORNING-NL-top01-thumbLarge.jpg",
			"format": "Large Thumbnail",
			"height": 150,
			"width": 150,
			"type": "image",
			"subtype": "photo",
			"caption": "A view of the U.S. Capitol from the Supreme Court.",
			"copyright": "Stefani Reynolds for The New York Times"
		}],
		"short_url": "https://nyti.ms/3PUNhwi"
	}],
      headers: { "content-type": "application/json" },
    },
    { overwriteRoutes: true }
  );
};
