export enum Articles {
    GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN',
    GET_ACCESS_TOKEN_SUCCESS = 'GET_ACCESS_TOKEN_SUCCESS',
    GET_ACCESS_TOKEN_FAIL = 'GET_ACCESS_TOKEN_FAIL',

    REGISTER_ACCESS_TOKEN = 'REGISTER_ACCESS_TOKEN',
    REGISTER_ACCESS_TOKEN_SUCCESS = 'REGISTER_ACCESS_TOKEN_SUCCESS',
    REGISTER_ACCESS_TOKEN_FAIL = 'REGISTER_ACCESS_TOKEN_FAIL',

    GET_ARTICLES = 'GET_ARTICLES',
    GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS',
    GET_ARTICLES_FAIL = 'GET_ARTICLES_FAIL',

    SEARCH_ARTICLE = 'SEARCH_ARTICLE',
    SEARCH_ARTICLE_SUCCESS = 'SEARCH_ARTICLE_SUCCESS',
    SEARCH_ARTICLE_FAIL = 'SEARCH_ARTICLE_FAIL',

    GET_TOP_ARTICLES = 'GET_TOP_ARTICLES',
    GET_TOP_ARTICLES_SUCCESS = 'GET_TOP_ARTICLES_SUCCESS',
    GET_TOP_ARTICLES_FAIL = 'GET_TOP_ARTICLES_FAIL',
}